name: "Push directory to another repository"
description: "Useful to push files to another repository to be used, for example, via github pages"
inputs:
  source-directory:
    description: "Source directory from the origin directory"
    required: true
  destination-github-repository-username:
    description: "Name of the destination GitHub username/organization"
    required: true
  destination-github-repository-name:
    description: "Name of the destination GitHub repository"
    required: true
  destination-repository-folder:
    description: "[Optional] Path to the folder of the destination repository the files should be committed"
    required: false
    default: "/"
  user-email:
    description: "Sets: git config --global user.email"
    required: true
  user-name:
    description: "Sets: git config --global user.name"
    required: true
  target-branch:
    description: '[Optional] set target branch name for the destination repository. Defaults to "master"'
    default: "master"
    required: false
  commit-message:
    description: "[Optional] commit message for the output repository. DEFAULT: Updated $DESTINATION_GITHUB_REPOSITORY_NAME from $GITHUB_REPOSITORY with user $USER_EMAIL"
    required: false

runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
      env:
        SOURCE_DIRECTORY: ${{ inputs.source-directory }}
        DESTINATION_GITHUB_REPOSITORY_USERNAME: ${{ inputs.destination-github-repository-username }}
        DESTINATION_GITHUB_REPOSITORY_NAME: ${{ inputs.destination-github-repository-name }}
        DESTINATION_REPOSITORY_FOLDER: ${{ inputs.destination-repository-folder }}
        USER_EMAIL: ${{ inputs.user-email }}
        USER_NAME: ${{ inputs.user-name }}
        TARGET_BRANCH: ${{ inputs.target-branch }}
        COMMIT_MESSAGE: ${{ inputs.commit-message }}

branding:
  icon: "git-commit"
  color: "green"
