name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  source-directory:
    description: 'Source directory from the origin directory'
    required: true
  destination-github-username:
    description: 'Name of the destination username/organization'
    required: true
  destination-repository-name:
    description: 'Destination repository'
    required: true
  user-email:
    description: 'Email for the git commit'
    required: true
  destination-repository-username:
    description: '[Optional] Username/organization for the destination repository'
    required: false
    default: ''
  target-branch:
    description: '[Optional] set target branch name for the destination repository. Defaults to "master"'
    default: 'master'
    required: false
  commit-message:
    description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
    required: false
  target-repo-directory:
    description: 'Target directory in the destination repository'
    required: false
runs:
  using: "composite"
  steps:
    - run: echo "SOURCE_DIRECTORY=${{ inputs.source-directory }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "DESTINATION_GITHUB_USERNAME=${{ inputs.destination-github-username }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "DESTINATION_REPOSITORY_NAME=${{ inputs.destination-repository-name }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "USER_EMAIL=${{ inputs.user-email }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "DESTINATION_REPOSITORY_USERNAME=${{ inputs.destination-repository-username }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "TARGET_BRANCH=${{ inputs.target-branch }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "COMMIT_MESSAGE=${{ inputs.commit-message }}" >> $GITHUB_ENV
      shell: bash
    - run: echo "TARGET_REPO_DIRECTORY=${{ inputs.target-repo-directory }}
      shell: bash
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
branding:
  icon: 'git-commit'
  color: 'green'
