name: 'Push directory to another repository'
description: 'Useful to push files to another repository to be used, for example, via github pages'
inputs:
  SOURCE_DIRECTORY:
    description: 'Source directory from the origin directory'
    required: true
  DESTINATION_GITHUB_USERNAME:
    description: 'Name of the destination username/organization'
    required: true
  DESTINATION_REPOSITORY_NAME:
    description: 'Destination repository'
    required: true
  USER_EMAIL:
    description: 'Email for the git commit'
    required: true
  DESTINATION_REPOSITORY_USERNAME:
    description: '[Optional] Username/organization for the destination repository'
    required: false
    default: ''
  TARGET_BRANCH:
    description: '[Optional] set target branch name for the destination repository. Defaults to "master"'
    default: 'master'
    required: false
  COMMIT_MESSAGE:
    description: '[Optional] commit message for the output repository. ORIGIN_COMMIT is replaced by the URL@commit in the origin repo'
    required: false
  TARGET_REPO_DIRECTORY:
    description: 'Target directory in the destination repository'
    required: false
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/entrypoint.sh
      shell: bash
branding:
  icon: 'git-commit'
  color: 'green'
